name: Agora
on: [push, pull_request]
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH into server
        env:
          PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.PROD_SSH_HOST }}
          USER_NAME: 'ubuntu'
        run: |
          echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              export NVM_DIR=~/.nvm &&
              export DJANGO_SETTINGS_MODULE=kernel.settings_prod &&
              . ~/.nvm/nvm.sh &&
              cd /home/ubuntu/agoragaming.gg &&
              . .venv/bin/activate &&
              sh bin/deploy prod
              '

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: SSH into server
        env:
          PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.DEV_SSH_HOST }}
          USER_NAME: 'ubuntu'
        run: |
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              export NVM_DIR=~/.nvm &&
              . ~/.nvm/nvm.sh &&
              cd /home/ubuntu/dev.agoragaming.gg &&
              . .venv/bin/activate &&
              sh bin/deploy
              '
